/**
 * Vellum — brand constants and motion utilities.
 *
 * Editorial restraint. Generous negative space. Times-Roman serif headlines.
 * No spring, no overshoot. Hairlines and warm paper.
 *
 * Generated by the upgraded code-generator agent using motion_design DNA
 * from brand-identity.json.
 */

import {
  delay,
  easeInOutCubic,
  easeOutCubic,
  easeOutQuint,
  linear,
  ThreadGenerator,
} from '@revideo/core';

// ─── Palette ──────────────────────────────────────────────────────────────
export const colors = {
  primary: '#1A1612',          // Deep Ink — headlines, body text
  secondary: '#6B6358',         // Warm Taupe — sublines
  accent: '#B85042',            // Terracotta — quiet emphasis only
  bgWarm: '#F4EFE6',            // Book Paper — primary background
  bgCream: '#ECE5D5',           // Aged Cream — mid-tone, card surfaces
  softNeutral: '#D9CFB8',       // Hairline Taupe — 1px dividers
  quiet: '#9C9385',             // Reader's Gray — micro-labels
  shadow: 'rgba(26, 22, 18, 0.05)',
} as const;

// ─── Typography ───────────────────────────────────────────────────────────
// Vellum uses serif for hero text. We use system serif stacks for portability
// during headless render — Times New Roman first, Georgia fallback.
export const fonts = {
  heading: 'Times New Roman, Georgia, serif',
  body: 'Georgia, serif',
  accent: 'Inter, sans-serif',  // tiny micro-labels only
} as const;

export const fontSizes = {
  hero: 144,        // very large — generous, magazine cover feel
  h1: 96,
  h2: 64,
  body: 28,
  caption: 18,
  label: 13,        // tiny micro-labels
  micro: 11,
} as const;

export const fontWeights = {
  heading: 400,     // serif weight is the natural weight; no bold
  body: 400,
  accent: 300,
} as const;

// ─── Timing (calm editorial pacing; from motion_design.pace) ──────────────
// Vellum's average beat is 0.55s — slow editorial pace.
export const timing = {
  beat: 0.55,             // average_beat_duration
  entrance: 0.4,
  fade: 0.45,
  hold: 0.6,              // generous breath — magazine pacing
  breathLong: 0.8,        // longest hold (end of section)
  microBeat: 0.1,
  charStagger: 0.06,      // editorial pace; slow but rendered in 14s budget
  exit: 0.45,
  cameraMove: 1.0,        // unhurried camera
  trackingTighten: 0.4,   // letter-spacing animation duration
} as const;

// ─── Effects ──────────────────────────────────────────────────────────────
export const effects = {
  shadowBlur: 50,
  shadowOpacity: 0.05,
  softGlowBlur: 180,       // very large blur for atmospheric haze
  softGlowOpacity: 0.18,
  divider: 1,              // 1px hairlines (exclusive)
  cardRadius: 2,           // almost sharp corners
  pillRadius: 999,
  trackingHero: 16,        // hero text starts LOOSE
  trackingTight: 4,        // tightens to this on emphasis
  trackingMicro: 12,       // sublabel max tracking
} as const;

// ─── Layout ───────────────────────────────────────────────────────────────
export const layout = {
  width: 1920,
  height: 1080,
  margin: 120,             // generous margin — editorial breathing room
  contentWidth: 1440,
  gutter: 60,
} as const;

// ─── Composition (rule of thirds — from technical-reference Section 32) ───
export const composition = {
  thirdX: layout.width / 3,
  thirdY: layout.height / 3,
  thirdsTL: [-layout.width / 3, -layout.height / 3] as [number, number],
  thirdsTR: [layout.width / 3, -layout.height / 3] as [number, number],
  thirdsBL: [-layout.width / 3, layout.height / 3] as [number, number],
  thirdsBR: [layout.width / 3, layout.height / 3] as [number, number],
  thirdsCenterL: [-layout.width / 3, 0] as [number, number],
  thirdsCenterR: [layout.width / 3, 0] as [number, number],
  thirdsTopM: [0, -layout.height / 3] as [number, number],
  thirdsBotM: [0, layout.height / 3] as [number, number],
} as const;

// ─── Stagger helpers (Section 21 of technical-reference) ──────────────────

/** Exponential stagger — accelerating reveal. */
export function staggerExp(
  generators: ThreadGenerator[],
  baseDelay = 0.05,
  factor = 1.5,
): ThreadGenerator[] {
  return generators.map((gen, i) =>
    delay(baseDelay * Math.pow(factor, i), gen) as ThreadGenerator,
  );
}

/** Wave stagger — sinusoidal distribution. */
export function staggerWave(
  generators: ThreadGenerator[],
  totalDuration = 1.0,
): ThreadGenerator[] {
  const n = generators.length;
  return generators.map((gen, i) => {
    const t = i / Math.max(1, n - 1);
    const offset = totalDuration * (t - 0.5 * Math.sin(2 * Math.PI * t) / (2 * Math.PI));
    return delay(offset, gen) as ThreadGenerator;
  });
}

/** Even march stagger — Vellum default is slow 0.10s. */
export function staggerMarch(
  generators: ThreadGenerator[],
  spacing = 0.10,
): ThreadGenerator[] {
  return generators.map((gen, i) => delay(i * spacing, gen) as ThreadGenerator);
}

/** Hairline divider color used throughout. */
export const dividerColor = colors.softNeutral;

/** Default easings exposed for consumers — Vellum uses easeOutQuint primarily. */
export const easings = {
  primary: easeOutQuint,
  secondary: easeInOutCubic,
  tertiary: easeOutCubic,
  linear,
} as const;

// ─── Notes ────────────────────────────────────────────────────────────────
//   Vellum motion_design specifies spring_config: 'none'. There are NO spring
//   imports/exports in this brand file. Use easeOutQuint (primary) instead.
//   No overshoot — never easeOutBack.
