/**
 * Forge — brand constants and motion utilities.
 *
 * Generated by the upgraded code-generator agent using motion_design DNA
 * from brand-identity.json. Indie game energy — overshoot everywhere,
 * particle bursts on every hero, glitch transitions, screen-shake on
 * impacts, vibrant accents. Pace is dense (0.22s beats), easing biased
 * to easeOutBack/easeOutExpo with heavy spring physics.
 */

import {
  delay,
  easeInOutCubic,
  easeOutCubic,
  easeOutBack,
  easeOutExpo,
  easeOutQuart,
  linear,
  ThreadGenerator,
} from '@revideo/core';

// ─── Palette ──────────────────────────────────────────────────────────────
export const colors = {
  primary: '#0A0E27',          // Cosmic Indigo — deep background
  accent: '#FF006E',           // Magenta Pulse — hero accent
  secondary: '#FFBE0B',        // Discovery Gold — discovery moments
  tertiary: '#3A86FF',         // Magic Blue — electric arcs
  bgDark: '#0F1335',           // Dungeon Black — card backgrounds
  bgMid: '#1B1F45',            // Mid Indigo — depth layers
  white: '#FFFFFF',            // Spell White — text, hero glyphs
  glow: '#FF4081',             // Glow Pink — atmospheric bloom
  shadow: 'rgba(255, 0, 110, 0.36)',
} as const;

// ─── Typography ───────────────────────────────────────────────────────────
// Bold display font with chunky character shapes (pixel-art aesthetic)
export const fonts = {
  heading: 'Impact, Helvetica Black, Arial Black, sans-serif',
  body: 'Inter, system-ui, sans-serif',
  accent: 'Inter, system-ui, sans-serif',
} as const;

export const fontSizes = {
  hero: 220,            // huge for FORGE wordmark
  h1: 96,
  h2: 64,
  body: 28,
  caption: 22,
  label: 18,
} as const;

export const fontWeights = {
  heading: 900,         // ultra-bold display
  body: 500,
  accent: 700,          // chunky labels
} as const;

// ─── Timing (high-energy; from motion_design.pace — beat 0.22s) ───────────
export const timing = {
  beat: 0.22,           // average_beat_duration
  entrance: 0.18,
  fade: 0.18,
  hold: 0.18,           // max 0.2s breath holds per spec — no long static holds
  microBeat: 0.05,
  exit: 0.18,
  cameraMove: 0.45,
  impact: 0.12,
  shakeStep: 0.04,
} as const;

// ─── Effects ──────────────────────────────────────────────────────────────
export const effects = {
  shadowBlur: 48,
  shadowOpacity: 0.4,
  glowBlurInner: 36,
  glowBlurMid: 80,
  glowBlurOuter: 180,
  strokeChunky: 3,
  cardRadius: 12,
  pillRadius: 6,
} as const;

// ─── Layout ───────────────────────────────────────────────────────────────
export const layout = {
  width: 1920,
  height: 1080,
  margin: 96,
  contentWidth: 1600,
} as const;

// ─── Composition (rule of thirds) ─────────────────────────────────────────
export const composition = {
  thirdX: layout.width / 3,
  thirdY: layout.height / 3,
  thirdsTL: [-layout.width / 3, -layout.height / 3] as [number, number],
  thirdsTR: [layout.width / 3, -layout.height / 3] as [number, number],
  thirdsBL: [-layout.width / 3, layout.height / 3] as [number, number],
  thirdsBR: [layout.width / 3, layout.height / 3] as [number, number],
} as const;

// ─── Spring Configs (HEAVY overshoot for indie game energy) ───────────────
// LogoLandSpring tuned high-overshoot — characters spring in with strong
// anticipation, settle past 1.0 then back. Used on every hero entrance.
export const LogoLandSpring = {
  mass: 0.05,
  stiffness: 22,
  damping: 0.42,         // low damping → big overshoot
  initialVelocity: 14,
} as const;

// UISpring snappy with one overshoot — portal pops, UI confirmations
export const UISpring = {
  mass: 0.05,
  stiffness: 30,
  damping: 0.55,
  initialVelocity: 9,
} as const;

// Punch spring for impact moments — fast settle
export const PunchSpring = {
  mass: 0.04,
  stiffness: 38,
  damping: 0.68,
  initialVelocity: 18,
} as const;

// ─── Helpers from technical-reference Section 21 ──────────────────────────

/** Exponential stagger — accelerating reveal. */
export function staggerExp(
  generators: ThreadGenerator[],
  baseDelay = 0.03,
  factor = 1.5,
): ThreadGenerator[] {
  return generators.map(
    (gen, i) => delay(baseDelay * Math.pow(factor, i), gen) as ThreadGenerator,
  );
}

/** Wave stagger — sinusoidal distribution. Middle items quicker, edges slower. */
export function staggerWave(
  generators: ThreadGenerator[],
  totalDuration = 0.8,
): ThreadGenerator[] {
  const n = generators.length;
  return generators.map((gen, i) => {
    const t = i / Math.max(1, n - 1);
    const offset = totalDuration * (t - 0.5 * Math.sin(2 * Math.PI * t) / (2 * Math.PI));
    return delay(offset, gen) as ThreadGenerator;
  });
}

/** Even march stagger — tight 0.04s default for dense pacing. */
export function staggerMarch(
  generators: ThreadGenerator[],
  spacing = 0.04,
): ThreadGenerator[] {
  return generators.map((gen, i) => delay(i * spacing, gen) as ThreadGenerator);
}

/** Standard hold beat after a section concludes (short for indie energy). */
export function holdBeat(): number {
  return timing.hold;
}

/** Compute drop-shadow blur for a hero element based on its size. */
export function heroShadowBlur(size: number): number {
  return Math.max(40, size * 0.15);
}

/** Default easings exposed for consumers. */
export const easings = {
  primary: easeOutBack,
  secondary: easeOutExpo,
  smooth: easeInOutCubic,
  punchy: easeOutQuart,
  ease: easeOutCubic,
  linear,
} as const;
