/**
 * Atlas — brand constants and motion utilities.
 *
 * Generated by the v2 code-generator using motion_design DNA from
 * brand-identity.json. Bold, kinetic, impact-driven. Heavy display
 * type, signal-orange accents, dramatic camera moves, count-up metrics.
 *
 * Pace: 0.22s beats (dense). Easing dominant: easeOutExpo + easeOutQuart.
 * Camera: whipPan / pushIn / pullOut, parallax enabled.
 */

import {
  delay, sequence,
  easeOutExpo, easeOutQuart, easeOutBack, easeOutQuint,
  easeInOutCubic, easeOutCubic, linear,
  ThreadGenerator,
} from '@revideo/core';

// ─── Palette ──────────────────────────────────────────────────────────────
export const colors = {
  primary: '#0B0F14',         // Track Black — backgrounds
  accent: '#FF4500',           // Signal Orange — PR/emphasis
  secondary: '#4ADE80',        // Electric Green — improvement
  warning: '#F87171',          // Caution Red
  bgDark: '#131820',           // Carbon Gray — cards
  bgMid: '#1F2A38',            // Slate Mid — panels
  white: '#F8FAFC',            // Track Chalk — primary text
  softGrey: '#94A3B8',         // Stadium Mist — labels
  shadow: 'rgba(0, 0, 0, 0.55)',
  accentShadow: 'rgba(255, 69, 0, 0.35)',
  gridLine: 'rgba(148, 163, 184, 0.12)',
} as const;

// Semantic data colors (technical-reference Section 32 — Color Animation Rules)
export const dataColors = {
  positive: colors.secondary,   // green — PR / improvement
  negative: colors.warning,     // red — caution
  neutral: colors.softGrey,
  emphasis: colors.accent,      // signal orange
} as const;

// ─── Typography ───────────────────────────────────────────────────────────
export const fonts = {
  heading: 'Inter',
  body: 'Inter',
  accent: 'Inter',
  // Mono falls back to Inter rendered with display weight (JetBrains Mono not bundled).
  // Inter has tabular numerals at heavy weights — looks like stadium signage.
  mono: 'Inter',
} as const;

export const fontSizes = {
  hero: 240,            // huge stadium metric (e.g. "21:47")
  display: 168,         // ATLAS logo display
  h1: 96,
  h2: 64,
  h3: 44,
  body: 24,
  caption: 18,
  label: 14,
} as const;

export const fontWeights = {
  display: 900,
  heading: 800,
  metric: 700,
  body: 500,
  accent: 700,
} as const;

// Optical tracking (technical-reference Section 30)
export const opticalTracking = {
  hero: -6,             // huge type wants very tight tracking
  display: -4,
  h1: -2.4,
  h2: -1.4,
  body: 0,
  caption: 0.4,
  labelUppercase: 5.2,  // wide eyebrow labels
} as const;

// ─── Timing (high energy; from motion_design.pace) ────────────────────────
export const timing = {
  beat: 0.22,           // average_beat_duration — dense
  entrance: 0.28,
  exit: 0.22,
  fade: 0.2,
  hold: 0.3,            // brief holds — no long breath
  microBeat: 0.08,
  cameraMove: 0.6,
  shake: 0.4,
  whipPan: 0.35,
} as const;

// ─── Effects ──────────────────────────────────────────────────────────────
export const effects = {
  shadowBlur: 80,
  shadowOpacity: 0.45,
  rimGlowBlur: 90,
  rimGlowIntensity: 0.55,
  innerGlowBlur: 24,
  midGlowBlur: 60,
  outerGlowBlur: 140,
  divider: 1.5,
  cardRadius: 14,
  pillRadius: 999,
  sparklineWidth: 3,
} as const;

// ─── Layout ───────────────────────────────────────────────────────────────
export const layout = {
  width: 1920,
  height: 1080,
  margin: 96,
  contentWidth: 1600,
} as const;

// Composition grid (technical-reference Section 33 — rule of thirds)
export const composition = {
  thirdX: layout.width / 3,
  thirdY: layout.height / 3,
  thirdsTL: [-layout.width / 3, -layout.height / 3] as [number, number],
  thirdsTR: [layout.width / 3, -layout.height / 3] as [number, number],
  thirdsBL: [-layout.width / 3, layout.height / 3] as [number, number],
  thirdsBR: [layout.width / 3, layout.height / 3] as [number, number],
  centerLeft: [-layout.width / 3, 0] as [number, number],
  centerRight: [layout.width / 3, 0] as [number, number],
  topMiddle: [0, -layout.height / 3] as [number, number],
  bottomMiddle: [0, layout.height / 3] as [number, number],
} as const;

// ─── Spring Configs (technical-reference Section 21) ──────────────────────
// Atlas uses UISpring as default — confident snap, mild overshoot allowed.
export const UISpring = {
  mass: 0.06,
  stiffness: 32,
  damping: 0.72,
  initialVelocity: 6,
} as const;

export const LogoLandSpring = {
  mass: 0.04,
  stiffness: 14,
  damping: 0.58,
  initialVelocity: 10,
} as const;

export const PunchSpring = {
  mass: 0.05,
  stiffness: 42,
  damping: 0.62,
  initialVelocity: 14,
} as const;

export const OrganicSpring = {
  mass: 0.08,
  stiffness: 8,
  damping: 0.7,
  initialVelocity: 2,
} as const;

// ─── Stagger helpers (kept for backwards compat with v1; v2 uses computeStagger) ──

/** Exponential stagger — accelerating reveal. */
export function staggerExp(
  generators: ThreadGenerator[],
  baseDelay = 0.04,
  factor = 1.6,
): ThreadGenerator[] {
  return generators.map((gen, i) =>
    delay(baseDelay * Math.pow(factor, i), gen) as ThreadGenerator,
  );
}

/** Wave stagger — sinusoidal distribution. Middle items quicker, edges slower. */
export function staggerWave(
  generators: ThreadGenerator[],
  totalDuration = 1.0,
): ThreadGenerator[] {
  const n = generators.length;
  return generators.map((gen, i) => {
    const t = i / Math.max(1, n - 1);
    const offset = totalDuration * (t - 0.5 * Math.sin(2 * Math.PI * t) / (2 * Math.PI));
    return delay(offset, gen) as ThreadGenerator;
  });
}

/** Even march stagger. */
export function staggerMarch(
  generators: ThreadGenerator[],
  spacing = 0.06,
): ThreadGenerator[] {
  return generators.map((gen, i) => delay(i * spacing, gen) as ThreadGenerator);
}

/** Standard hold beat after a section concludes. */
export function holdBeat(): number {
  return timing.hold;
}

/** Drop-shadow blur for a hero element based on its size. */
export function heroShadowBlur(size: number): number {
  return Math.max(48, size * 0.18);
}

/** Default easings exposed for consumers. */
export const easings = {
  primary: easeOutExpo,
  secondary: easeOutQuart,
  accent: easeOutBack,
  transition: easeInOutCubic,
  smooth: easeOutCubic,
  linear,
  quint: easeOutQuint,
} as const;
