/**
 * Lumen — brand constants and motion utilities.
 *
 * Generated by the upgraded code-generator agent using motion_design DNA
 * from brand-identity.json. Calm, premium, editorial. No overshoot.
 */

import { delay, easeInOutCubic, easeOutCubic, ThreadGenerator } from '@revideo/core';

// ─── Palette ──────────────────────────────────────────────────────────────
export const colors = {
  primary: '#1F2A26',         // Forest Dusk — headlines, deep text
  secondary: '#7A9E8E',        // Sage Mist — supporting illustration
  accent: '#D4B98C',           // Warm Linen — highlights
  bgLight: '#F7F4EC',          // Calm Cream — primary background
  bgWhite: '#FBFBF8',          // Off-white — cards
  softNeutral: '#E8E2D5',      // Stone Whisper — dividers
  shadow: 'rgba(31, 42, 38, 0.04)',
} as const;

// ─── Typography ───────────────────────────────────────────────────────────
export const fonts = {
  heading: 'Inter',
  body: 'Inter',
  accent: 'Inter',
} as const;

export const fontSizes = {
  hero: 96,
  h1: 64,
  h2: 44,
  body: 24,
  caption: 18,
  label: 14,
} as const;

export const fontWeights = {
  heading: 500,
  body: 400,
  accent: 300,
} as const;

// ─── Timing (calm; from motion_design.pace) ───────────────────────────────
export const timing = {
  beat: 0.45,           // average_beat_duration
  entrance: 0.35,
  fade: 0.4,
  hold: 0.6,            // generous holds — calm pacing
  microBeat: 0.12,
  exit: 0.4,
  cameraMove: 1.2,
} as const;

// ─── Effects ──────────────────────────────────────────────────────────────
export const effects = {
  shadowBlur: 60,
  shadowOpacity: 0.06,
  softGlowBlur: 80,
  softGlowOpacity: 0.18,
  divider: 1,            // 1px hairlines
  cardRadius: 24,
  pillRadius: 999,
} as const;

// ─── Layout ───────────────────────────────────────────────────────────────
export const layout = {
  width: 1920,
  height: 1080,
  margin: 96,
  contentWidth: 1440,
} as const;

// ─── Composition Grid (v2) ────────────────────────────────────────────────
const _thirdX = layout.width / 3;
const _thirdY = layout.height / 3;
export const composition = {
  thirdX: _thirdX,
  thirdY: _thirdY,
  thirdsTL: [-_thirdX, -_thirdY] as [number, number],
  thirdsTR: [_thirdX, -_thirdY] as [number, number],
  thirdsBL: [-_thirdX, _thirdY] as [number, number],
  thirdsBR: [_thirdX, _thirdY] as [number, number],
  centerLeft: [-_thirdX, 0] as [number, number],
  centerRight: [_thirdX, 0] as [number, number],
  topMiddle: [0, -_thirdY] as [number, number],
  bottomMiddle: [0, _thirdY] as [number, number],
  asymmetricPadding: 120,
} as const;

// ─── Spring Configs (from technical-reference Section 21) ─────────────────
// Lumen uses OrganicSpring exclusively — soft, floaty, no overshoot character
export const LogoLandSpring = {
  mass: 0.04,
  stiffness: 12,
  damping: 0.6,
  initialVelocity: 8,
} as const;

export const UISpring = {
  mass: 0.05,
  stiffness: 25,
  damping: 0.85,
  initialVelocity: 4,
} as const;

export const OrganicSpring = {
  mass: 0.08,
  stiffness: 8,
  damping: 0.7,
  initialVelocity: 2,
} as const;

// ─── Helpers from technical-reference Section 21 ──────────────────────────

/** Exponential stagger — accelerating reveal. */
export function staggerExp(
  generators: ThreadGenerator[],
  baseDelay = 0.04,
  factor = 1.6,
): ThreadGenerator[] {
  return generators.map((gen, i) =>
    delay(baseDelay * Math.pow(factor, i), gen) as ThreadGenerator,
  );
}

/** Wave stagger — sinusoidal distribution. Middle items quicker, edges slower. */
export function staggerWave(
  generators: ThreadGenerator[],
  totalDuration = 1.0,
): ThreadGenerator[] {
  const n = generators.length;
  return generators.map((gen, i) => {
    const t = i / Math.max(1, n - 1);
    const offset = totalDuration * (t - 0.5 * Math.sin(2 * Math.PI * t) / (2 * Math.PI));
    return delay(offset, gen) as ThreadGenerator;
  });
}

/** Even march stagger — 0.08s default. */
export function staggerMarch(
  generators: ThreadGenerator[],
  spacing = 0.08,
): ThreadGenerator[] {
  return generators.map((gen, i) => delay(i * spacing, gen) as ThreadGenerator);
}

/** Hairline divider color used in cards and section breaks. */
export const dividerColor = colors.softNeutral;

/** Standard hold beat after a section concludes. */
export function holdBeat(): number {
  return timing.hold;
}

/** Compute drop-shadow blur for a hero element based on its size. */
export function heroShadowBlur(size: number): number {
  return Math.max(40, size * 0.15);
}

/** Default easings exposed for consumers. */
export const easings = {
  primary: easeInOutCubic,
  secondary: easeOutCubic,
} as const;
